### ISSUE TITLE
Issue with build folder

### ISSUE THREAD

**Issue by xuankhanh** [acro5piano/react-native-big-calendar#1019]
I have tried to use "yarn build" command and it has successfully generated a build folder:
![error1](https://github.com/acro5piano/react-native-big-calendar/assets/9045077/f79aa20d-039c-40d6-a129-2f862c17e9dd)
![2024-03-13_14-05-41](https://github.com/acro5piano/react-native-big-calendar/assets/9045077/4ebdfaa8-0398-4962-8397-e5405eabb234)

Then when I run the demo project, I got this error. It seems there is some issue with building project because there is nothing in index.es.js. 
![error2](https://github.com/acro5piano/react-native-big-calendar/assets/9045077/174f8688-a909-488c-b2ab-d45f4d924fdc)

Are there anything I missed here ? Thanks for your support !

**Comment by acro5piano** [comment]
Sorry for my slow response.

You need to run `yarn sync-rndemo` to update the code in the react native demo app. This is required because Metro bundler cannot load parent directory.

If you have any questions, feel free to re-open this issue. Thanks

**Comment by xuankhanh** [comment]
@acro5piano when I run "yarn sync-rndemo", I got this error:
![2024-03-19_12-02-52](https://github.com/acro5piano/react-native-big-calendar/assets/9045077/e510ba9d-8c5f-4387-9509-64fd5d06b41d)

Do you know what I am missing ? Thanks for your support !

**Comment by acro5piano** [comment]
Hmm, that should be related to Windows platform. Can you try cleaning the build and cache directories and try again?
