### ISSUE TITLE
event cell position problem of minHour & maxHour

### ISSUE THREAD

**Issue by jangminhyeok** [acro5piano/react-native-big-calendar#1053]
when I set minHour and maxHour, event cell's position is not proper. (mode=week)
For example, 15:00-16:00 event goes to 17:00-18:00 when I set minHour to 9 and maxHour to 21.
I checked it in iOS 17.4 / iPhone 15 Pro Max.

**Comment by acro5piano** [comment]
@jangminhyeok Thanks for reporting. Can you provide a screenshot, reproductive code or storybook?

@adambinnersley Any chance to look into it?

**Comment by acro5piano** [comment]
Fixed on v4.13.2. Thank you @comeonlnw !
