### ISSUE TITLE
A feature request for the calender body renderer

### ISSUE THREAD

**Issue by muneeb-250** [acro5piano/react-native-big-calendar#1072]
Hi, I want to implement a functionality using this calendar such that on the `week` mode, I want the Calendar body to render only the selected day column from the week, not the whole week columns. Is there any workaround to do it in the current version?

**Comment by acro5piano** [comment]
Hi, it's possible by using `custom` mode. Please take a look at the storybook and corresponding source code.

https://react-native-big-calendar.vercel.app/?path=/story/showcase-desktop--custom-week-length

Thank you.
