### ISSUE TITLE
Events on Sundays Not Displaying in Month View

### ISSUE THREAD

**Issue by Pinkesh26** [acro5piano/react-native-big-calendar#1094]
When using the react-native-big-calendar package in month mode, events that fall on Sundays are not displayed properly. The same events are displayed correctly in week and day modes but do not appear in the month view.

const myevents = [
   {
    title: 'Meeting',
    start: new Date(2024, 8, 1),  // Sunday, September 1, 2024
    end: new Date(2024, 8, 1),
    color: '#dedaff',
  },
  {
    title: 'Workshop',
    start: new Date(2024, 8, 8),  // Sunday, September 8, 2024
    end: new Date(2024, 8, 8),
    color: '#dedaff',
  },
    {
      title: 'Bill new',
      start: new Date(2024, 8, 21),  
      end: new Date(2024, 8, 21),
      color: '#dedaff',
    },
    {
      title: 'Willie new',
      start: new Date(2024, 8, 12),  
      end: new Date(2024, 8, 12),
      color: '#dedaff',
    },
    // Add more events as needed
  ];
  
    <Calendar
            events={myevents}
            height={600}
            weekStartsOn={0} // Sunday
            mode="month"
          />

**Comment by Pinkesh26** [comment]
setting millisecond like 'new Date(item.date).setHours(0, 0, 0, 1);' solve the issue.

**Comment by acro5piano** [comment]
@Pinkesh26 Thanks for sharing your solution

**Comment by CalciumPotato** [comment]
I'm having this issue too (v4.18.4). When sortedMonthView is **true**, the event items on Sunday would disappear if it's **end** time smaller or equal than the current time, even though the event date is not even the same with current date. For example, when the current time is 10:56 (Tested on 2025-07-14 **Monday**), the item will be displayed properly on the calendar. However, if the current time is 10:55, the item will not be displayed. I guess maybe something's wrong with sortedEvents in CalendarBodyForMonthView but unfortunately I'm new to coding and can't even try to fix it myself.
Example events: [
  {
    "color": "#111111",
    "type": "appointment",
    "start": "2025-07-13T04:54:00.000Z",
    "end": "2025-07-13T04:55:00.000Z",
    "title": "Test Sunday 1 - booked"
  }
]
I'm kinda new to this, please let me know if you need more info.

**Comment by filippozanfini** [comment]
This only happens to me if the first day of a new month falls on a Sunday and coincides with the end of the previous month. I don't know how to solve this.

<img width="229" height="364" alt="Image" src="https://github.com/user-attachments/assets/52506a00-2fc3-46d8-ba4f-7bccf26ed5ea" />
