### ISSUE TITLE
How to set 12 hours time format

### ISSUE THREAD

**Issue by JogiPrasadPakki** [acro5piano/react-native-big-calendar#129]
This is nice library how to set time to 12 hours format instead of 24 hour format

**Comment by acro5piano** [comment]
Thank you for your kind words.

The feature you mentioned is not implemented yet, but your PR is welcome.

As a reference, I'd like to share which file should be changed to implement it:

https://github.com/llotheo/react-native-big-calendar/blob/master/src/CalendarBody.tsx#L38-L45

**Comment by JoeKlimcak** [comment]
+1

**Comment by acro5piano** [comment]
I've implemented in https://github.com/acro5piano/react-native-big-calendar/pull/246
