### ISSUE TITLE
Additional Styling Enhancements

### ISSUE THREAD

**Issue by JoeKlimcak** [acro5piano/react-native-big-calendar#243]
Can we please consider adding the following styling TODOs:

- Ability to customize the hour sidebar (colors, fonts etc)
- Ability to customize the font in an event cell
- Ability to customize grid line style

**Comment by acro5piano** [comment]
Yes the ability should be implemented.

**Comment by sebastienfi** [comment]
> Ability to customize the font in an event cell

This is fixed in https://github.com/acro5piano/react-native-big-calendar/pull/359

**Comment by acro5piano** [comment]
As I've published `v2.0.0-rc` and implemented this topic, I'll close this issue. If you have bugs on it, feel free to report it!

https://github.com/acro5piano/react-native-big-calendar/releases/tag/v2.0.0-rc

Summary: You can now use `theme` prop.
