### ISSUE TITLE
Issue with swiping left and right

### ISSUE THREAD

**Issue by Osher671279** [acro5piano/react-native-big-calendar#247]
Hey,
First, i would like to say that i love the lib and the work you have done here
There is a small problem i would like to address you with,

My goal is to swipe the dates correctly, meaning:
When i swipe my finger Left i want to it to advance in the dates forward and not render the previous ones
And to other side accordingly

Please if you dont understand something tell me

Adding a video:

[Video to explain](https://vimeo.com/462057700)

**Comment by acro5piano** [comment]
Hi, thanks for your interest in this project.

Do you mean swiping more naturally, like google calendar app? 
I agree with you, and there is a longstanding issue.

https://github.com/acro5piano/react-native-big-calendar/issues/138

I think react-native-reanimated (or native Animated) will solve the issue. I really appreciate if you do it.

**Comment by acro5piano** [comment]
Duplicated #138
