### ISSUE TITLE
Any plan to support mode "Month" in the near future?

### ISSUE THREAD

**Issue by angelos3lex** [acro5piano/react-native-big-calendar#288]
First of all Thanks a lot for this lib! A current block for us is that it doesn't support "month" mode type.
Are there any plans for it in the near future?

**Comment by acro5piano** [comment]
Thanks for your interest. I'll definitely support Month view, but don't
have enough resource for it. If you send a PR I am happy to merge it.

**Comment by acro5piano** [comment]
Released `month` mode on v1.0.1.
