### ISSUE TITLE
Dynamic colors of events

### ISSUE THREAD

**Issue by nyblad** [acro5piano/react-native-big-calendar#324]
Is it possible to set own backgroundColors for the events passed from events-array? How to use the prop eventCellStyle to change the color dynamic?

If I have data like:
```
title: event.title,
start: event.start,
end: event.end,
color: event.colorCode
```

**Comment by acro5piano** [comment]
Hi @nyblad ! Thanks for your interest. Yes, you can add each cell style dynamically by passing a function to `eventCellStyle`.

Like this:

```tsx
<Calendar
  height={600}
  events={events}
  eventCellStyle={event => ({ backgroundColor: event.colorCode })}
/>
```

See more:

https://github.com/acro5piano/react-native-big-calendar/blob/41a6b00079b930c8442af1ddc199d26f0e1a6260/stories/desktop.stories.tsx#L60-L67

**Comment by acro5piano** [comment]
Feel free to reopen if you still have a question.

**Comment by arya2311** [comment]
how to change text color dynamic generated event

**Comment by acro5piano** [comment]
@arya2311 

Same analogy.

```tsx
 <Calendar 
   style={styles.calendar} 
   height={SCREEN_HEIGHT} 
   events={events} 
   eventCellStyle={(event) => { 
     const color = event.title.match(/Meeting/) ? 'red' : 'blue' 
     return { color } 
   }} 
```

**Comment by chinmay4github1987** [comment]
I am using the above approach to integrate but not getting the color changed.
<Calendar
        theme={darkTheme}
        mode={'month'}
        hideNowIndicator={false}
        startAccessor="start"
        endAccessor="end"
        events={calendarEvents}
        eventCellStyle= {(event) => { 
        const backgroundColor = event.reg.match(true) ? 'red' : 'blue' 
        return { backgroundColor }
        }
      }
        date={date}
      />

**Comment by JessyAngel07** [comment]
> @arya2311
> 
> Same analogy.
> 
> ```tsx
>  <Calendar 
>    style={styles.calendar} 
>    height={SCREEN_HEIGHT} 
>    events={events} 
>    eventCellStyle={(event) => { 
>      const color = event.title.match(/Meeting/) ? 'red' : 'blue' 
>      return { color } 
>    }} 
> ```

@acro5piano  how to change position of the event in event cell

**Comment by acro5piano** [comment]
@JessyAngel07 Try to set `marginTop` or `top`. If it does not work, try to use `renderEvent` to get the full control of rendering logic.

**Comment by shahzaibali01** [comment]
@acro5piano when i use renderEvent it add event at the end of calend not in the speicifice time
