### ISSUE TITLE
Wrong object type on BaseEvent

### ISSUE THREAD

**Issue by odyodyodys** [acro5piano/react-native-big-calendar#336]
`BaseEvent` has `start` and `end` fields defined as `Date`.

The event `onPressEvent` from `Calendar` component emits a `BaseEvent` object.
That instance seems to have its `start` and `end` fields as DayJs objectes instead of `date`.

**Comment by acro5piano** [comment]
@odyodyodys 
Thanks for your interest in this project. 
I've confirmed that your comment is correct. I'll fix it soon!

**Comment by acro5piano** [comment]
Fixed in v0.7.3.

@odyodyodys 

Can you check it in the newest version?
