### ISSUE TITLE
Cell Height?

### ISSUE THREAD

**Issue by ShooterArk** [acro5piano/react-native-big-calendar#338]
Hi, 
First of all thank you for such a great plugin. 

Is it possible to change the height of the cell? I tried using eventcellstyle but it didnt work. Please advise.

Thank you.

**Comment by acro5piano** [comment]
@ShooterArk 
Thank you for your interest in this library.
It is calculated by the height of calendar. Try change `height` prop of `<Calendar />`.

**Comment by ShooterArk** [comment]
@acro5piano thank you for quick response my friend. 

I studied your plugin code, did find out that the cell height is binded with the height in the props but it causes the problem for me as the cell height gets changed for the complete calendar including the height of the header so I reviewed the code and made the necessary changes for myself. 

I would request if possible can you please add cellHeight in the props as well for the Calendar body. My requirement was to show 10 mins slots which was not possible in current unless I changed the cell height so that I can properly see big 10 mins slot. 

regards,

**Comment by acro5piano** [comment]
@ShooterArk Thank you for the details. Can you create a PR for this? I would like to merge it.

**Comment by from0toweb** [comment]
I really need this opportunity, I still do not have enough knowledge to find the dependency in the source code

**Comment by from0toweb** [comment]
I really need this opportunity, I still do not have enough knowledge to find the dependency in the source code

**Comment by acro5piano** [comment]
Hopefully I'll work on this weekend.

**Comment by RajRohitYadav** [comment]
@acro5piano I can help with this. Is this about the minimum height for the event card, or one specific cell height, or complete row height?

**Comment by acro5piano** [comment]
@RajRohitYadav 
Thank you very much!

> Is this about the minimum height for the event card, or one specific cell height, or complete row height?

I read OP @ShooterArk 's comment again, but I couldn't interpret his comment one specific cell height or overall cell height.

I think we should implement a prop as `function` which receives `event: ICalendarEvent` and returns `cellHeight: number`, just like  `eventCellStyle` does. I will cover both cases and quite flexible.

**Comment by acro5piano** [comment]
It could be configured by `renderEvent` props. Feel free to reopen if you still want it.
