### ISSUE TITLE
Make sure object exists before using scrollTo method

### ISSUE THREAD

**Issue by filipearena** [acro5piano/react-native-big-calendar#351]
Hi there, 

First of all thanks a lot for creating and maintaining this repo, it has been really helpful! :)

That being said, I've encountered an issue when using the prop scrollOffsetMinutes:

<img width="383" alt="Screen Shot 2021-03-08 at 3 50 31 pm" src="https://user-images.githubusercontent.com/6992650/110280557-bcd32980-8026-11eb-82b1-49ac5edcc54a.png">

I think to fix that, it would only require to the following change (double checking the object exists before using the scrollTo method):

![Screen Shot 2021-03-08 at 3 58 02 pm](https://user-images.githubusercontent.com/6992650/110280748-15a2c200-8027-11eb-975b-a387454c65aa.png)

Cheers

**Comment by acro5piano** [comment]
@filipearena Thank you for reporting it. Can you create a PR for this? It should be helpful.

**Comment by filipearena** [comment]
@acro5piano thanks for the quick reply. 

Here is the PR for it: https://github.com/acro5piano/react-native-big-calendar/pull/352

**Comment by acro5piano** [comment]
Released in v0.7.5. Thank you for your contribution!!

https://github.com/acro5piano/react-native-big-calendar/releases/tag/v0.7.5
