### ISSUE TITLE
Cannot use eventRenderer with react-native and expo

### ISSUE THREAD

**Issue by titanve** [acro5piano/react-native-big-calendar#388]
Good morning.

# Description
I'm trying to use the eventRenderer function in the events array but it doesn't work, would you please help me to know what I'm doing wrong? The main objective is to style the event cell individually (font-size by task time span).

# Screencapture
![image](https://user-images.githubusercontent.com/4803351/115877995-a8e45b00-a40d-11eb-8435-fe0da17b085b.png)

![image](https://user-images.githubusercontent.com/4803351/115878031-b4378680-a40d-11eb-86d4-441643cf80a6.png)

**Comment by acro5piano** [comment]
Hi, if you just change style based on event time span, you can pass a
function to style props.

**Comment by acro5piano** [comment]
Hi, if you just change style based on event time span, you can pass a
function to style props.

Sorry it was `eventCellStyle`.

So the code should look like this:

```tsx
<Calendar
  eventCellStyle={event => ({ fontSize: Number(event.end) - Number(event.start) })}
/>
```

**Comment by acro5piano** [comment]
Sorry `eventCellStyle` won't work on platforms other than Web.

@titanve 
What is your code contains `<Calendar />`? And what will happen if you add some style to `<Text />` in your code?

@sebastienfi 
Do you have any thoughts on this?

**Comment by titanve** [comment]
Good morning,

This is what I have:
![image](https://user-images.githubusercontent.com/4803351/115959804-a9472980-a4d3-11eb-9458-4f7ce1a973f0.png)

**Comment by acro5piano** [comment]
@titanve 
Good morning. The code should work.
Have you tried adding some style to `<Text />` in your `eventRenderer`?

**Comment by acro5piano** [comment]
And I found the current implementation is not ideal. Created an issue for it.

https://github.com/acro5piano/react-native-big-calendar/issues/389

**Comment by titanve** [comment]
@acro5piano 

I added styling but nothing changed:
![image](https://user-images.githubusercontent.com/4803351/115972664-627a2380-a515-11eb-9f29-9efe3a28799e.png)

**Comment by titanve** [comment]
Hello,

I just upgraded to version 0.9.1 and it worked!
![image](https://user-images.githubusercontent.com/4803351/115980899-c1f82380-a555-11eb-9613-f6c7071d6209.png)


Thank you.
