### ISSUE TITLE
weekStartsOn 1 not working when switching from day to week view

### ISSUE THREAD

**Issue by mikeschoneveld** [acro5piano/react-native-big-calendar#423]
When I set weekStartsOn to 1 and the weeks starts on Monday the week is shown correctly but when the day view is active on a Sunday and I switch to the week view it shows me the week after instead of the current week.

**Comment by acro5piano** [comment]
Thanks for reporting. I'll check it later.

**Comment by acro5piano** [comment]
Released on v1.0.2
