### ISSUE TITLE
Calendar layout with mode="month"

### ISSUE THREAD

**Issue by ThangKillah** [acro5piano/react-native-big-calendar#443]
when i try calendar with mode ="month" the layout seems incorrect, other mode work fine: 
![Screenshot_20210614-160302](https://user-images.githubusercontent.com/33564881/121867298-05873680-cd2a-11eb-9b4d-52f83a69c190.png)

**Comment by acro5piano** [comment]
That's too bad. We should fix the hard coded part.

**Comment by priami93** [comment]
Same problem

**Comment by acro5piano** [comment]
#444

**Comment by acro5piano** [comment]
Fixed by #466

**Comment by acro5piano** [comment]
The fix has been released on v1.0.3
