### ISSUE TITLE
Month View for Mobile is not available

### ISSUE THREAD

**Issue by umarmansuri** [acro5piano/react-native-big-calendar#444]
I need to create a month view with calendar events which is available on desktop demo

https://react-native-big-calendar.netlify.app/?path=/story/desktop--month-mode

**Comment by acro5piano** [comment]
Thanks for reporting. We should fix this

**Comment by umarmansuri** [comment]
is possible to get the solution soon? @acro5piano

**Comment by acro5piano** [comment]
Sorry I have marriage ceremony on early July so I'll work after it.
If you send a PR for this, I'll happy to merge!

**Comment by acro5piano** [comment]
The fix has been released on v1.0.3

**Comment by umarmansuri** [comment]
Hi @acro5piano 
Thanks for the solution I update my code but having one issue of white spacing in the Calendar Component
And please share how to increase the height and width of the cell too
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/3337060/126768874-1c60f6cd-2e83-4752-b5bd-91f5baf19f4e.png)

**Comment by acro5piano** [comment]
@umarmansuri Which version do you use?

**Comment by umarmansuri** [comment]
latest version which you just published under #466 v1.0.3

**Comment by acro5piano** [comment]
![Screenshot_20210725_191118_com rndemo](https://user-images.githubusercontent.com/10719495/126895544-e2ca18d5-8bbb-4654-abe9-665b42f31217.jpg)

That's strange. I can see this screen. Can you post your code and environment?

**Comment by acro5piano** [comment]
Please try the new version (above v2.0.0) again.
