### ISSUE TITLE
ampm mode does not apply to events

### ISSUE THREAD

**Issue by sr0409** [acro5piano/react-native-big-calendar#445]
![Screenshot_20210629-223704](https://user-images.githubusercontent.com/46093425/123977915-0902fa80-d985-11eb-8505-c8ccc0265e24.jpg)

**Comment by sr0409** [comment]
In my opinion it will make sense to apply the ampm mode to events as well.

**Comment by acro5piano** [comment]
I agree with your suggestion!

**Comment by acro5piano** [comment]
As I've published `v2.0.0-rc` and implemented this topic, I'll close this issue. If you have bugs on it, feel free to report it!

https://github.com/acro5piano/react-native-big-calendar/releases/tag/v2.0.0-rc

Summary: Fixed it.
