### ISSUE TITLE
Is it possible to get different event like Leave meeting, Complete Meeting Or Drop meeting?

### ISSUE THREAD

**Issue by umarmansuri** [acro5piano/react-native-big-calendar#468]
Hi
 I need to make some business logic in my app after completing the Meeting or the event of the Leave meeting? But I am not able to found any events to capture and do this.
Will you please help in this

**Comment by umarmansuri** [comment]
Sorry its my bad this issue is not related with this

**Comment by acro5piano** [comment]
I'm glad you fixed the issue on your own.
For others, it would be great if you share what you did!
