### ISSUE TITLE
Encountered two children with the same key

### ISSUE THREAD

**Issue by juspeeh** [acro5piano/react-native-big-calendar#472]
The key for event generated with the logic `key={'${event.start}${event.title}'}`. I have a case where there can be multiple events with exactly same details. This results in a react warning. 

Maybe index be added to the combination to prevent this from happening?

**Comment by acro5piano** [comment]
Hi, thanks for the interest. Yes it should be fixed. Can you send a PR for this? Maybe index is enough, but adding `keyExtractor` is ideal.

https://reactnative.dev/docs/flatlist#keyextractor

**Comment by acro5piano** [comment]
As I've published `v2.0.0-rc` and implemented this topic, I'll close this issue. If you have bugs on it, feel free to report it!

https://github.com/acro5piano/react-native-big-calendar/releases/tag/v2.0.0-rc

Summary: I've added ${event.end} too. It's rare that the collision happens.
