### ISSUE TITLE
Can we add some css class to calender header. Need to hide it in one of usecase

### ISSUE THREAD

**Issue by mindbodysolotestfirebase** [acro5piano/react-native-big-calendar#473]
Need to hide calendar header which shows date. Any ways to do it? Can we provide any class to handle css

**Comment by acro5piano** [comment]
Hi, thanks for your interest in this project.

What do you mean by "hide"? Does it means to remove the element entirely, or make it invisible?
In either way, there is no way to do it for now, I'll work on improve it soon. I'll add this to the to-do list.

**Comment by mindbodysolotestfirebase** [comment]
Thanks @acro5piano for replying. Yes means customized css classes for calendar header so that we can make css changes

**Comment by VinitSarvade** [comment]
I would like to take this up @acro5piano. Will send out a PR shortly.

**Comment by acro5piano** [comment]
@VinitSarvade Fantastic! Could you implement it by adding `renderCalendarHeader` prop? It should accept appropriate date range.
It makes the component more flexible. Thanks!

**Comment by acro5piano** [comment]
@VinitSarvade 
@mindbodysolotestfirebase 

I'm working on this PR and will release `v3.0.0-beta` soon.

https://github.com/acro5piano/react-native-big-calendar/pull/475

**Comment by acro5piano** [comment]
As I've published `v2.0.0-rc` and implemented this topic, I'll close this issue. If you have bugs on it, feel free to report it!

https://github.com/acro5piano/react-native-big-calendar/releases/tag/v2.0.0-rc
