### ISSUE TITLE
All Day Events not working for events more than 1 day

### ISSUE THREAD

**Issue by walidbezzaoui** [acro5piano/react-native-big-calendar#508]
I've tried to use all day events, it works properly if it's 1 day event, as long as you add an event that takes more than 1 day it always display the first day only.
For Example, from your story book, if you add 3 days in the end date it doesn't work. only shows the event in the start date.
    const _events = [
      ...events,
      {
        title: 'Vacation',
        start: dayjs().add(1, 'day').set('hour', 0).set('minute', 0).toDate(),
        end: dayjs().add(3, 'day').set('hour', 0).set('minute', 0).toDate(),
      },
    ]

**Comment by acro5piano** [comment]
Hi, I confirmed the issue.

The current render method of all-day event should be re-written to include all day.

https://github.com/acro5piano/react-native-big-calendar/blob/71ae5cdbaabf2cf344114f074105e5c85f1f2503/src/components/CalendarHeader.tsx#L106-L125

Deeply related: https://github.com/acro5piano/react-native-big-calendar/issues/456

**Comment by walidbezzaoui** [comment]
@acro5piano here is a pr for the fix:
https://github.com/acro5piano/react-native-big-calendar/pull/509/files

**Comment by acro5piano** [comment]
Released on https://github.com/acro5piano/react-native-big-calendar/releases/tag/v2.1.1
Thanks for your contribution!
