### ISSUE TITLE
Events not displaying in the calendar with RenderEvent

### ISSUE THREAD

**Issue by TeeRa0ne** [acro5piano/react-native-big-calendar#547]
Hi,

I create a renderEvent function and the events are displaying on the bottom of the calendar : 
![Screenshot_2021-11-18-14-33-38-093](https://user-images.githubusercontent.com/60188443/142425775-ce934dd7-231b-4a88-b01e-a66937ab587c.jpeg)

My code : 

<img width="632" alt="Capture d’écran 2021-11-18 à 14 40 50" src="https://user-images.githubusercontent.com/60188443/142426138-db2d7410-4dfb-4615-bec2-41f0fccdc78e.png">

Can you help me or any ideas ?

Thanks !

**Comment by acro5piano** [comment]
Hi, thanks for your interest in this project!

I think you should assign the `touchableOpacityProps`.

```ts
const renderEvent = (
  event: ICalendarEvent<MyCustomEventType>,
  touchableOpacityProps: CalendarTouchableOpacityProps,
) => (
  <RN.TouchableOpacity
    {...touchableOpacityProps}
    {/* ...other props */}
  >
```

**Comment by TeeRa0ne** [comment]
Thanks you for you're reply, i add the touchableOpacityProps but it doesn't work... :(
``` js
const renderEvent = (
    event,
    touchableOpacityProps,
    ) => {
    return (
      <RN.TouchableOpacity
        {...touchableOpacityProps}
        onPress={() => setIsOpen(true)}
        style={[
          {
            backgroundColor: 'white',
            borderWidth: 1,
            borderColor: '#3094FF',
            borderLeftColor: 'green',
            borderLeftWidth: 10,
            borderStyle: 'solid',
            borderRadius: 5,
            alignItems: 'center',
            margin: 5,
            justifyContent: 'center',
          },
        ]}
      >
```

**Comment by acro5piano** [comment]
The style is overwritten. Please try the following:

```
const renderEvent = (
    event,
    touchableOpacityProps,
    ) => {
    return (
      <RN.TouchableOpacity
        {...touchableOpacityProps}
        onPress={() => setIsOpen(true)}
        style={[
          {
            backgroundColor: 'white',
            borderWidth: 1,
            borderColor: '#3094FF',
            borderLeftColor: 'green',
            borderLeftWidth: 10,
            borderStyle: 'solid',
            borderRadius: 5,
            alignItems: 'center',
            margin: 5,
            justifyContent: 'center',
            ...touchableOpacityProps.style,
          },
        ]}
      >
```

**Comment by TeeRa0ne** [comment]
It's dosen't work,

My calendar balise :
``` js
<Calendar renderEvent={renderEvent} theme={jabiTheme} swipeEnabled={false} locale="fr" mode={calendarMode} events={events} height={900}></Calendar>
```

My render event :
``` js
const renderEvent = (
    event,
    touchableOpacityProps,
  ) => {
    return (
      <RN.TouchableOpacity
        {...touchableOpacityProps}
        onPress={() => setModalOpen(true)}
        style={[
          {
            backgroundColor: 'white',
            borderWidth: 1,
            borderColor: '#3094FF',
            borderLeftColor: 'green',
            borderLeftWidth: 10,
            borderStyle: 'solid',
            borderRadius: 5,
            alignItems: 'center',
            margin: 5,
            justifyContent: 'center',
            ...touchableOpacityProps.style,
          },
        ]}
      >
        <>
          <RN.Text style={[{ color: 'black', fontSize: 19 }]}>{event.title}</RN.Text>
          <RN.Text style={[{ color: 'black', fontSize: 18 }]}>
            {dayjs(event.start).format('HH:mm')} - {dayjs(event.end).format('HH:mm')}
          </RN.Text>
        </>
      </RN.TouchableOpacity>
    )
  }
```

**Comment by TeeRa0ne** [comment]
My bad the props that I had declared were not correct. 

Thanks you for you're help !

**Comment by acro5piano** [comment]
Glad to hear that!

**Comment by pranavaccion** [comment]
hi i used same function but still all my events are showing in bottom

**Comment by acro5piano** [comment]
@pranavaccion 
Please share your code fully. I can't help you unless you share it.

**Comment by pranavaccion** [comment]
const events = [
	{
		id: 0,
		title: 'All Day Event very long title',
		allDay: true,
		start: new Date(2021, 11, 22),
		end: new Date(2021, 11, 22),
		type: 'In',
	},
	{
		id: 1,
		title: 'Long Event',
		start: new Date(2021, 11, 7),
		end: new Date(2021, 11, 10),
		type: 'in',
	},

	{
		id: 2,
		title: 'DTS STARTS',
		start: new Date(2016, 2, 13),
		end: new Date(2016, 2, 20),
		type: 'tele',
	},

	{
		id: 11,
		title: 'DTS ENDS',
		start: new Date(2016, 10, 6),
		end: new Date(2016, 10, 13),
		type: 'in',
	},

	{
		id: 4,
		title: 'Some Event',
		start: new Date(2021, 11, 9),
		end: new Date(2021, 11, 10),
		type: 'in',
	},
	{
		id: 5,
		title: 'Conference',
		start: new Date(2021, 11, 11),
		end: new Date(2021, 11, 13),
		desc: 'Big conference for important people',
		type: 'tele',
	},
	{
		id: 6,
		title: 'Meeting',
		start: new Date(2021, 11, 12, 10, 30, 0, 0),
		end: new Date(2021, 11, 12, 12, 30, 0, 0),
		desc: 'Pre-meeting meeting, to prepare for the meeting',
		type: 'in',
	},
	{
		id: 7,
		title: 'Lunch',
		start: new Date(2021, 11, 12, 12),
		end: new Date(2021, 11, 12, 13),
		desc: 'Power lunch',
		type: 'in',
	},
	{
		id: 8,
		title: 'Meeting',
		start: new Date(2021, 11, 12, 14),
		end: new Date(2021, 11, 12, 15),
	},
	{
		id: 9,
		title: 'Happy Hour',
		start: new Date(2021, 11, 12, 17),
		end: new Date(2021, 11, 12, 17, 30, 0, 0),
		desc: 'Most important meal of the day',
	},
	{
		id: 10,
		title: 'Dinner',
		start: new Date(2021, 11, 12, 20),
		end: new Date(2021, 11, 12, 21),
		type: 'in',
	},
	{
		id: 11,
		title: 'Planning Meeting with Paige',
		start: new Date(2021, 11, 13, 8, 0, 0),
		end: new Date(2021, 11, 13, 10, 30, 0),
	},
	{
		id: 11.1,
		title: 'Inconvenient Conference Call',
		start: new Date(2021, 11, 13, 9, 30, 0),
		end: new Date(2021, 11, 13, 12, 0, 0),
	},
	{
		id: 11.2,
		title: "Project Kickoff - Lou's Shoes",
		start: new Date(2021, 11, 13, 11, 30, 0),
		end: new Date(2021, 11, 13, 14, 0, 0),
		type: 'in',
	},
	{
		id: 11.11,
		title: 'Quote Follow-up - Tea by Tina',
		start: new Date(2021, 11, 13, 15, 30, 0),
		end: new Date(2021, 11, 13, 16, 0, 0),
	},
	{
		id: 12,
		title: 'Late Night Event',
		start: new Date(2021, 11, 17, 19, 30, 0),
		end: new Date(2021, 11, 18, 2, 0, 0),
		allDay: true,
	},
	{
		id: 12.5,
		title: 'Late Same Night Event',
		start: new Date(2021, 11, 17, 19, 30, 0),
		end: new Date(2021, 11, 17, 23, 30, 0),
	},
	{
		id: 13,
		title: 'Multi-day Event',
		start: new Date(2021, 11, 20, 19, 30, 0),
		end: new Date(2021, 11, 27, 2, 0, 0),
	},
	{
		id: 14,
		title: 'Today',
		start: new Date(new Date().setHours(new Date().getHours() - 11)),
		end: new Date(new Date().setHours(new Date().getHours() + 11)),
	},
	{
		id: 16,
		title: 'Video Record',
		start: new Date(2021, 11, 14, 11, 30, 0),
		end: new Date(2021, 11, 14, 12, 0, 0),
	},
	{
		id: 17,
		title: 'Dutch Song Producing',
		start: new Date(2021, 11, 14, 12, 30, 0),
		end: new Date(2021, 11, 14, 13, 0, 0),
	},
	{
		id: 18,
		title: 'Itaewon Halloween Meeting',
		start: new Date(2021, 11, 14, 13, 30, 0),
		end: new Date(2021, 11, 14, 14, 30, 0),
	},
	{
		id: 19,
		title: 'Online Coding Test',
		start: new Date(2021, 11, 14, 15, 30, 0),
		end: new Date(2021, 11, 14, 16, 30, 0),
	},
	{
		id: 20,
		title: 'An overlapped Event',
		start: new Date(2021, 11, 14, 16, 10, 0),
		end: new Date(2021, 11, 14, 17, 20, 0),
	},
	{
		id: 21,
		title: 'Phone Interview',
		start: new Date(2021, 11, 14, 20, 30, 0),
		end: new Date(2021, 11, 14, 21, 30, 0),
	},
	{
		id: 22,
		title: 'Cooking Class',
		start: new Date(2021, 11, 14, 17, 30, 0),
		end: new Date(2021, 11, 14, 19, 0, 0),
		type: 'in',
	},
	{
		id: 23,
		title: 'Go to the gym',
		start: new Date(2021, 11, 14, 19, 30, 0),
		end: new Date(2021, 11, 14, 20, 0, 0),
		type: 'in',
	},
];
const renderEvent = (event, touchableOpacityProps) => {
		console.log('touchableOpacityProps', touchableOpacityProps);
		return (
			<TouchableOpacity
				{...touchableOpacityProps}
				onPress={() => console.log('tr')}
				style={{
					...touchableOpacityProps.style,
					marginBottom: 20,
				}}
			>
				<Text>{event.title}</Text>
			</TouchableOpacity>
		);
	};

**Comment by pranavaccion** [comment]
hey @acro5piano it is working now once I separated render event comp from parent component. just have one doubt can I colour code event background based on event type ??

**Comment by pranavaccion** [comment]
![Screenshot 2021-12-24 at 6 05 02 PM](https://user-images.githubusercontent.com/84321162/147353019-93d1d47a-ccff-4e23-a395-1333543437e3.png)

**Comment by pranavaccion** [comment]
@acro5piano thank you in advance ..waiting for response

**Comment by acro5piano** [comment]
@pranavaccion 
Glad to see you resolved the issue on your own. 

> can I colour code event background based on event type

I think you can use `eventCellStyle` for that.
