### ISSUE TITLE
Support for current react native versions?

### ISSUE THREAD

**Issue by lorenzogatti** [acro5piano/react-native-big-calendar#568]
React Native 0.59 was released in March 2019. Do you plan to support current versions of React Native? Is there some incompatibility? I'm very uncomfortable running obsolete React and React Native versions for the sake of this component.

Thank you

**Comment by lorenzogatti** [comment]
If I understand NPM dependency resolution correctly, specifying versions with a caret allows versions that are at least the specified one but before the next major version: any 0.59.x (I think the last of the line is 0.59.8) is OK because it's considered a corrected 0,59,0, but 0.60 and later are incompatible.  

This is because the first component of the version number of React Native is 0, making the second component the important one; React itself is locked to 16.x.y for x >=8 and y>=3 or x>=9 (rather than 16.8.z for z>=3) by specifying "^16.8.3"

Reference: https://semver.npmjs.com/ to see version patterns applied to actual versions of actual packages

**Comment by acro5piano** [comment]
> This is because the first component of the version number of React Native is 0, making the second component the important one

Oh really, I didn't notice that. Thanks for letting me know! Can you propose proper syntax and hopefully create a PR for this? Thanks

**Comment by lorenzogatti** [comment]
Using >= instead of > would include all newer versions
 
"peerDependencies": {
    "react": ">=16.8.3",
    "react-native": ">=0.59.0"
},

But it's quite a bold commitment because new major versions with breaking changes would be automatically included.

Multiple ranges, adding recent major versions after proper testing and removing old ones as they become unsupported, should be more appropriate; hopefully...

"peerDependencies": {
    "react": "^16.8.3||^17.0.0",
    "react-native": "^0.59.0||^0.60.0||^0.61.0||^0.62.0||^0.63.0||^0.64.0||^0.65.0||^0.66.0"
},

Thank you again

**Comment by acro5piano** [comment]
Thanks!

As this library does not depends on a specific version of React Native, something like this should be okay for now?

https://github.com/invertase/react-native-firebase/blob/main/packages/app/package.json#L54-L57

**Comment by lorenzogatti** [comment]
With an asterisk, the specification becomes even looser than with a minimum version.

There are, necessarily, minimum required versions of React and React Native (probably so old that you never tested them, and older than you should bother supporting); allowing ancient incompatible versions that no one actually uses any more except by mistake is quite low risk.

The real problem is with future incompatible React and React Native versions: locking them out by default should be useful to manage expectations, since users upgrading base libraries would get a version mismatch error and upgrade react-native-big-calendar, without blaming you because react-native-big-calendar is advertised as compatible but it doesn't work.

**Comment by acro5piano** [comment]
I understand. Please send a PR if you want.
