### ISSUE TITLE
eventCellStyle not updating the background color of event

### ISSUE THREAD

**Issue by vipulbuoyancy** [acro5piano/react-native-big-calendar#574]
eventCellStyle not updating the background color of event.

Here is my code

const getEventColor=()=>{
   return {backgroundColor:"#111", color:"#fff"};
}

<Calendar
          height={Dimensions.get('window').height - 60}
          events={[...getEvent]}
          mode={mode}          
          eventCellStyle={()=>{ getEventColor()}}
          swipeEnabled={true}
          onPressEvent={() => { SetShowModal(true) }}
        />

Please help me and let me know what I am doing wrong over here.

Thank you.

**Comment by acro5piano** [comment]
I think you should remove the curly brace around the expression.

**Comment by girish-floorzap** [comment]
Thanks @acro5piano it is working as expected without curly brace.

**Comment by acro5piano** [comment]
The complete code should be like this. If you use static cell style, you should use `StyleSheet.create` for better performance.

```tsx
const styles = StyleSheet.create({
  eventCell: {backgroundColor:"#111", color:"#fff"};
})

<Calendar
  height={Dimensions.get('window').height - 60}
  events={[...getEvent]}
  mode={mode}
  eventCellStyle={styles.eventCell}
  swipeEnabled={true}
  onPressEvent={() => { SetShowModal(true) }}
/>
```

If you have still any issues, please re-open!
