### ISSUE TITLE
Multiple day event in Month view onPressEvent is just working on first day and not on remaining days

### ISSUE THREAD

**Issue by girish-floorzap** [acro5piano/react-native-big-calendar#577]
When we have a multiple day event onPressEvent is just firing for first day of the event and not firing for remaining days.

Please have a look at attached image. In the image, we have multiple day event from 28th to 31st. so when we click on 28th onPressEvent will work fine but it will not work on remaining days of 29,30 & 31.

![Screenshot 2021-12-24 at 5 31 48 PM](https://user-images.githubusercontent.com/96039705/147351372-93db8b7d-0edc-43d4-a995-7480f1df7093.png)

Please have a look if you can help me with this. 

Also one suggestion, we can see cell breakout in between multiday events, it would be great if we can show the contineous event across the multiple days.
 
Once again Thanks a lot for previous issue.

**Comment by acro5piano** [comment]
Thanks for reporting it.

I'll fix it soon.

**Comment by acro5piano** [comment]
Fixed on v2.9.1

@girish-floorzap Can you check it again?

**Comment by girish-floorzap** [comment]
yes, it is working now. Thanks a lot for quick fix.
