### ISSUE TITLE
Is there any way to provide functionality of changing the year?

### ISSUE THREAD

**Issue by sk1794** [acro5piano/react-native-big-calendar#579]
I want to provide buttons for changing year and also month, is there any way i can do that?

**Comment by acro5piano** [comment]
Hi, you can use `date` prop and change it manually.

https://github.com/acro5piano/react-native-big-calendar/blob/d93bc11783f5b6cce0cd1f86cde881a4b40f1e07/stories/desktop.stories.tsx#L140-L157

If you have questions, feel free to ask here.
