### ISSUE TITLE
height prop doesn't do anything

### ISSUE THREAD

**Issue by davidaik** [acro5piano/react-native-big-calendar#605]
I installed the module and included the component in my React Native app.

    function Schedule() {
      return (
        <View style={{ height: '100%' }}>
          <Calendar events={[]} height={100} />
        </View>
      );
    }

The `height` prop doesn't do anything. The result is the same whether I set it to 50, 80, 100 or 120.

I'm on React Native `0.63.4` and OS is Android 11.

**Comment by acro5piano** [comment]
You should specify absolute height of your calendar as a number. Please
calculate actual height using Dimension.
