### ISSUE TITLE
[QUESTION] What is the empty space in the header?

### ISSUE THREAD

**Issue by davidaik** [acro5piano/react-native-big-calendar#606]
![calendar](https://user-images.githubusercontent.com/16955921/148206243-f7f0a3f1-77f0-41f6-94cd-c0e11591890b.jpg)
Hi. I've just gotten started with this wonderful module, and I was wondering about the empty space that is in the header? I marked it in the image above. Does it serve a purpose? I was thinking that maybe it would be better to make the date and day appear closer to the bottom border?

**Comment by acro5piano** [comment]
Hi @davidaik, thanks for your interest. The space is reserved for all-day events and currently no way to hide it. If you create a pull request for that, I'm happy to merge it. Thanks!

**Comment by davidaik** [comment]
Thanks for the response, @acro5piano. I'll try introducing an option to hide that empty space.

**Comment by acro5piano** [comment]
Sorry I forgot it, but `showAllDayEventCell` property may do it.

**Comment by davidaik** [comment]
It worked! Thank you so much, @acro5piano!
