### ISSUE TITLE
Duplicate key for the events

### ISSUE THREAD

**Issue by shailesh896** [acro5piano/react-native-big-calendar#607]
in your current code the key used in  CalendarEvent in the calendar body component doesn't guaranty unicity.
<CalendarEvent
      key={`${event.start}${event.title}${event.end}`}
       ...../>
 it gives error saying multiple children with same key found when two events with same title are booked on same start and end time.
I know it is a rare case but we get cases with no title up front.  
so, could you use index or pass a key prop to make it unique.

**Comment by acro5piano** [comment]
Please send a PR for that. Thanks
