### ISSUE TITLE
date prop

### ISSUE THREAD

**Issue by shailesh896** [acro5piano/react-native-big-calendar#608]
on passing the date prop it throws error:

Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    in _CalendarContainer (created by _Calendar)
    in _Calendar (at Calendar.tsx:122)
    in EventCalendar (at SlotSelection/index.tsx:141)
    in RCTView (at View.js:34)
    in View
    in Unknown (at createAnimatedComponent.js:448)
    in AnimatedComponent(Component) (at createAnimatedComponent.js:459)
    in AnimatedComponentWrapper (at SlotSelection/index.tsx:140)
    in SlotSelection (at SceneView.tsx:122)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RNSScreen (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at src/index.native.tsx:147)
    in Screen (at Screens.tsx:74)
    in MaybeScreen (at CardStack.tsx:616)
    in RNSScreenContainer (at src/index.native.tsx:186) .......

removing the date dependency might work.

**Comment by acro5piano** [comment]
I think you are missing `useCallback` to your function. I can't help you unless you share whole code. Thanks

**Comment by shailesh896** [comment]
Calander.tsx 

import React, { useCallback, useState } from 'react'
import { Dimensions } from 'react-native'

import {
  ApolloClient,
  ApolloQueryResult,
  useApolloClient
} from '@apollo/client'
import Calendar, { ICalendarEvent } from 'react-native-big-calendar'
import { useFocusEffect, useNavigation } from '@react-navigation/core'

import { getScheduledActivities as getScheduledActivitiesQuery } from 'api/graphql/query/activities'
import { Objective, ScheduledActivitiesType } from 'types/inspiration'
import { Slot } from 'types/planning'

const { height } = Dimensions.get('window')

interface CalendarEventType {
  borderColor?: string
  color?: string
  id: number | string | null
  objective: Objective
  slotId: string
}

type Event = ICalendarEvent<CalendarEventType>

type Props = {
  data: Slot[]
  onPressEvent?(slotId: string | number): void
}

const mapEvents = (data: Slot[]): Event[] => {
  const events: Event[] = data.map(item => {
    return {
      color: item.parentObjective?.color,
      end: new Date(item.end || ''),
      id: item.activity?.id || '',
      start: new Date(item.start || ''),
      title: item.activity?.name,
      objective: item.parentObjective,
      slotId: item.slotId
    }
  })

  return events || []
}

const mapScheduledActivitiesToEvents = (
  data?: ScheduledActivitiesType
): Event[] => {
  const events: Event[] | undefined = data?.scheduledActivities.map(
    scheduledActivity => {
      return {
        borderColor: scheduledActivity.objective.color,
        color: '#ccc',
        end: new Date(scheduledActivity.end),
        id: scheduledActivity.id,
        start: new Date(scheduledActivity.start),
        title: scheduledActivity.activity.name
      }
    }
  )

  return events || []
}

const getScheduledActivities = async (
  apolloClient: ApolloClient<unknown>,
  weekStartEnd: Date[]
) => {
  const data = await apolloClient.query({
    query: getScheduledActivitiesQuery,
    variables: {
      where: {
        start_gte: weekStartEnd[0],
        end_lte: weekStartEnd[1]
      }
    },
    fetchPolicy: 'network-only'
  })

  return data as ApolloQueryResult<ScheduledActivitiesType>
}

const eventCellStyle = (event: Event) => {
  return {
    borderWidth: 2,
    borderColor: event.borderColor ? event.borderColor : event.color,
    backgroundColor: event.color
  }
}

const EventCalendar: React.FC<Props> = ({ data, onPressEvent }) => {
  const [scheduledEvents, setScheduledEvents] = useState<Event[]>([])
  const [weekStartEnd, setWeekStartEnd] = useState<Date[]>([])

  const apolloClient = useApolloClient()

  const navigation = useNavigation()
  const events = mapEvents(data)

  const fetchScheduledActivities = useCallback(() => {
    ;(async () => {
      try {
        const res = await getScheduledActivities(apolloClient, weekStartEnd)

        setScheduledEvents(mapScheduledActivitiesToEvents(res.data))
      } catch (err) {
        if (err.message.includes('status code 401')) {
          console.log('401 unauthorized')
        }
      }
    })()
  }, [apolloClient, weekStartEnd])

  useFocusEffect(fetchScheduledActivities)

  const allEvents = events.concat(scheduledEvents)

  return (
    <Calendar
      events={allEvents}
      height={height}
      weekStartsOn={1}
      eventCellStyle={eventCellStyle}
      showTime={false}
      onChangeDate={setWeekStartEnd}
      onPressEvent={event => {
        if (event.slotId) {
          onPressEvent && onPressEvent(event.slotId)

          navigation.navigate('Planning', {
            screen: 'NeedsSelection'
          })
        }
      }}
    />
  )
}

export default EventCalendar

**Comment by acro5piano** [comment]
@shailesh896 Thanks for providing the code. Can you wrap the `onPressEvent` function with `useCallback`?

**Comment by shailesh896** [comment]
so i added the useCallback , not sure if this what you asked,but the error persist. could youyhelp


import React, { useCallback, useState } from 'react'
import { Dimensions } from 'react-native'

import {
  ApolloClient,
  ApolloQueryResult,
  useApolloClient
} from '@apollo/client'
import Calendar, { ICalendarEvent } from 'react-native-big-calendar'
import { useFocusEffect, useNavigation } from '@react-navigation/core'

import { getScheduledActivities as getScheduledActivitiesQuery } from 'api/graphql/query/activities'
import { Objective, ScheduledActivitiesType } from 'types/inspiration'
import { Slot } from 'types/planning'

const { height } = Dimensions.get('window')

interface CalendarEventType {
  borderColor?: string
  color?: string
  id: number | string | null
  objective: Objective
  slotId: string
}

type Event = ICalendarEvent<CalendarEventType>

type Props = {
  data: Slot[]
  onPressEvent?(slotId: string | number): void
}

const mapEvents = (data: Slot[]): Event[] => {
  const events: Event[] = data.map(item => {
    return {
      color: item.parentObjective?.color,
      end: new Date(item.end || ''),
      id: item.activity?.id || '',
      start: new Date(item.start || ''),
      title: item.activity?.name,
      objective: item.parentObjective,
      slotId: item.slotId
    }
  })

  return events || []
}

const mapScheduledActivitiesToEvents = (
  data?: ScheduledActivitiesType
): Event[] => {
  const events: Event[] | undefined = data?.scheduledActivities.map(
    scheduledActivity => {
      return {
        borderColor: scheduledActivity.objective.color,
        color: '#ccc',
        end: new Date(scheduledActivity.end),
        id: scheduledActivity.id,
        start: new Date(scheduledActivity.start),
        title: scheduledActivity.activity.name
      }
    }
  )

  return events || []
}

const getScheduledActivities = async (
  apolloClient: ApolloClient<unknown>,
  weekStartEnd: Date[]
) => {
  const data = await apolloClient.query({
    query: getScheduledActivitiesQuery,
    variables: {
      where: {
        start_gte: weekStartEnd[0],
        end_lte: weekStartEnd[1]
      }
    },
    fetchPolicy: 'network-only'
  })

  return data as ApolloQueryResult<ScheduledActivitiesType>
}

const eventCellStyle = (event: Event) => {
  return {
    borderWidth: 2,
    borderColor: event.borderColor ? event.borderColor : event.color,
    backgroundColor: event.color
  }
}

const EventCalendar: React.FC<Props> = ({ data, onPressEvent }) => {
  const [scheduledEvents, setScheduledEvents] = useState<Event[]>([])
  const [weekStartEnd, setWeekStartEnd] = useState<Date[]>([])

  const apolloClient = useApolloClient()

  const navigation = useNavigation()
  const events = mapEvents(data)

  const fetchScheduledActivities = useCallback(() => {
    ;(async () => {
      try {
        const res = await getScheduledActivities(apolloClient, weekStartEnd)

        setScheduledEvents(mapScheduledActivitiesToEvents(res.data))
      } catch (err) {
        if (err.message.includes('status code 401')) {
          console.log('401 unauthorized')
        }
      }
    })()
  }, [apolloClient, weekStartEnd])

  useFocusEffect(fetchScheduledActivities)

  const allEvents = events.concat(scheduledEvents)

  const onPres = useCallback(event => {
    if (event.slotId) {
      onPressEvent && onPressEvent(event.slotId)

      navigation.navigate('Planning', {
        screen: 'NeedsSelection'
      })
    }
  }, [])

  return (
    <Calendar
      date={events[events.length - 1]?.start}
      events={allEvents}
      height={height}
      weekStartsOn={1}
      eventCellStyle={eventCellStyle}
      showTime={false}
      onChangeDate={setWeekStartEnd}
      onPressEvent={event => {
        onPres(event)
      }}
      scrollOffsetMinutes={events[events.length - 1]?.start.getHours() * 60}
    />
  )
}

export default EventCalendar

**Comment by shailesh896** [comment]
Hi, acro5piano can you confirm whether its a bug or not !

**Comment by acro5piano** [comment]
You seems not to understand how to use `useCallback`. If you pass an arrow function to child component, it break all benefits of `useCallback`. So try again with

```typescript
    <Calendar
      date={events[events.length - 1]?.start}
      events={allEvents}
      height={height}
      weekStartsOn={1}
      eventCellStyle={eventCellStyle}
      showTime={false}
      onChangeDate={setWeekStartEnd}
      onPressEvent={onPres}
      scrollOffsetMinutes={events[events.length - 1]?.start.getHours() * 60}
    />
```

**Comment by shailesh896** [comment]
Oh my mistake sorry for that and thanks for the solution and knowledge, it works fine now. thanks a lot.

**Comment by acro5piano** [comment]
@shailesh896 Glad to hear that!
