### ISSUE TITLE
Wrong event.endDate if event last longer than a week.

### ISSUE THREAD

**Issue by roggyboy** [acro5piano/react-native-big-calendar#609]
Hi. 
If an event lasts longer than a week the end date calculation is wrong when in month view. 
Have you ever seen this problem before? 

![image](https://user-images.githubusercontent.com/97289277/148537580-ce3d46ca-e400-4583-96a0-29248bb12fe6.png)

**Comment by acro5piano** [comment]
Sorry for my slow response and thanks for reporting it.

I haven't seen the issue yet, but if you send a pull request I'm happy to merge it. Thanks!

**Comment by Pakile** [comment]
@roggyboy I have the same issue, Do you have any solutions?

**Comment by roggyboy** [comment]
Hi. I have not tried to find a workaround for this because we found this bug when we tried different calendar frameworks to see how we wanted our calendar page to look. So this resulted in that we went for an other solution using react-native-calendars.

**Comment by acro5piano** [comment]
Fixed on v3.2.3
Thank you @Pakile

**Comment by riyaE2** [comment]
In End Date not showing perfectly.

![image](https://user-images.githubusercontent.com/112611651/187908696-dc4f56ba-95ac-44f5-ad8e-f5e335155655.png)

{
    "title": "Jay Jani",
    "start": "2022-09-19T09:30:00.000Z",
    "end": "2022-09-20T05:30:00.000Z",
    "color": "#FF8F79"
  },
  
  My start date is 19th sep and end date is 20th sep but i'm showing only 19th september event.
