### ISSUE TITLE
Issue with merge-anything

### ISSUE THREAD

**Issue by CptMaumau** [acro5piano/react-native-big-calendar#630]
I couldn't build my React Native project anymore due to an issue with merge-anything :
`While trying to resolve module 'merge-anything'... this package itself specifies a 'main' module field that could not be resolved`

I managed to fix this by changing the dependency in package.json from `^4.0.2` to `4.0.2`.

**Comment by acro5piano** [comment]
Thanks for reporting. Can you create a PR for it?

**Comment by CptMaumau** [comment]
Done! #631

**Comment by acro5piano** [comment]
@CptMaumau Thanks for you pull request. It's merged and fixed on v3.0.1. If you have any trouble, please re-open this issue. Thanks!

**Comment by acro5piano** [comment]
Fixed on v3.4.2. I removed `merge-anything` module completely. If you are using the hacky patch-package workaround, please stop using it and try the latest version.
