### ISSUE TITLE
onChangeDate infinite loop

### ISSUE THREAD

**Issue by CptMaumau** [acro5piano/react-native-big-calendar#632]
When I set up both `date` and `onChangeDate` props I get an infinite loop (onChangeDate is always triggered).
For example :
```
<Calendar
  ...
  date={moment().toDate()}
  onChangeDate={this.updateCalendar}
  ...
/>
```

I might be doing something wrong, any idea?

**Comment by acro5piano** [comment]
Are you using class component? We've tested code with only functional component. so my suggestion is

- Use function component.
- Wrap `updateCalendar` function with `useCallback`.

**Comment by CptMaumau** [comment]
Ha yes my calendar component is still a Class component, I was supposed to refactor it to functional anyway. I hope it will fix it.

**Comment by CptMaumau** [comment]
@acro5piano I have changed my component to functional component and wrapped `updateCalendar` with useCallback but I still get a loop... It actually happens because I have an API await call in my callback, still trying to figure why it does that.
