### ISSUE TITLE
InternalError Metro has encountered an error: While trying to resolve module `merge-anything` from file

### ISSUE THREAD

**Issue by Hwangseungwoo** [acro5piano/react-native-big-calendar#660]
Even I installed merge-anything, I encountered this error.

Do you know How to fix?

**Comment by acro5piano** [comment]
Thanks for reporting.
Are you using the yarn workspace or a similar tool?

**Comment by filipgerat** [comment]
Hello, I've encountered the same issue. We use npm not yarn. I fixed it by downgrading merge-anything to 4.0.2. Not ideal, but it worked

**Comment by acro5piano** [comment]
It's strange - the version of `merge-anything` is fixed with `4.0.2`. How did you downgrade it?

**Comment by filipgerat** [comment]
Yeah well, npm installed the 4.0.5 for some reason, so I added merge-anything to my projects package.json with the fixed 4.0.2 version.
Note: even with `npm I merge-anything@4.0.2` the version in package json was saved as `^4.0.2` so I edited it afterwards

**Comment by mubashiralisiddiqui** [comment]
@acro5piano I am also facing this issue it was working fine but today when I reinstall my modules I am getting this error
<img width="397" alt="image" src="https://user-images.githubusercontent.com/16689214/196925704-28eebf07-9f7d-4c84-a763-068793401f39.png">

**Comment by mubashiralisiddiqui** [comment]
I am able to fix my issue by adding 
 sourceExts: ['jsx', 'js', 'ts', 'tsx', 'cjs','svg'],
 in metro.confing.js file
<img width="574" alt="image" src="https://user-images.githubusercontent.com/16689214/196929889-7788f7d1-b4fa-42f1-94b9-d4c165951776.png">

**Comment by mmujtabam** [comment]
@mubashiralisiddiqui Can you please explain what this will do? Any disadvantage of this?

**Comment by acro5piano** [comment]
Fixed on v3.3.3

**Comment by acro5piano** [comment]
Fixed on v3.4.2. I removed `merge-anything` module completely. If you are using the hacky patch-package workaround, please stop using it and try the latest version.
