### ISSUE TITLE
Alternate way to pass start date with different format like 'YYYY-MM-DD' instead of new Date(2022, 08, 09) in month mode

### ISSUE THREAD

**Issue by gani419** [acro5piano/react-native-big-calendar#730]
Hi,
First of all thank you for providing the library.
I have a small issue where I'm getting data as '2022-08-08' format from server. I'm unable to convert to `**new Date(2022, 08, 08)**` in month mode.
Can you suggest me an alternate approach of providing the start date in the date or help me in converting the required format.
Thank you.

**Comment by acro5piano** [comment]
Thanks for your interest. I think you should simply convert the text into `Date` object before passing the calendar component.

**Comment by gani419** [comment]
thanks for the response.
I will try once.

**Comment by gani419** [comment]
In tried your process. But i'm getting the following error. Can you please check where I'm wrong.
![Screenshot_20220809-200524_StudentRN](https://user-images.githubusercontent.com/42198259/183677250-c7bd3a1e-965a-4c18-93df-74686a569669.png)

**Comment by gani419** [comment]
This is my data after converting start date in to date object.

[{"branch_name": "jklj", "class_timing_name": "weekday", "course_name": "Communication", "key": 100, "regcode": "J123", "registered": false, "start": "2022-08-08T18:30:00.000Z", "subject_name": "react", "title": "Communication-react", "trainer_name": {"id": 123, "username": "tr@gmail.com"}},]

**Comment by acro5piano** [comment]
as the error says, you need to define `end` property on your event

**Comment by gani419** [comment]
I'm sorry to disturb you, But I'm stuck here. I'm using mode as month and when the event start date is next month or previous then it is crashing even though I use end date. I'm showing sample events and it's implementation in Calendar. Please check.
My requirement is I have to display all events from current date to future dates and months.

Events:

`const eve = [
    {
      key: 101,
      title: 'techhhh-tech',
      course_name: 'techhhh',
      subject_name: 'tech',
      branch_name: 'Bazaar',
      class_timing_name: 'weekday',
      trainer_name: {
        id: 100,
        username: 'trainer@gmail.com',
      },
      start: '2022-09-10',
     end: '2022-09-10',
    },
    {
      key: 102,
      title: 'tech-tech',
      course_name: 'tech',
      subject_name: 'tech',
      branch_name: 'gandhi bazzar',
      class_timing_name: 'weekday',
      trainer_name: {
        id: 102,
        username: 'trainerkarnataka@gmail.com',
      },
      start: '2022-08-10',
      end: '2022-08-10',
    },
    {
      key: 103,
      title: 'big data',
      course_name: 'big data',
      subject_name: 'science',
      branch_name: 'Karnataka',
      class_timing_name: 'weekday',
      trainer_name: {
        id: 103,
        username: 'jammutrainer2@qsp.com',
      },
      start: '2022-08-10',
     end: '2022-08-10',
    },
  ];`

Calendar Implementation:

`<Calendar
        theme={darkTheme}
        onPressEvent={event => {
          alert(event.title);
        }}
        // mode="month"
        startAccessor="start"
        endAccessor="end"
        events={eve}
        height={600}
        date={date}
      />`

Below is the exception what I'm facing.
![Screenshot_20220810-132357_StudentRN 1](https://user-images.githubusercontent.com/42198259/183846856-55d2282e-e444-401f-bc80-c59858f537cd.png)

**Comment by gani419** [comment]
Actually I'm getting events displayed properly in week and other modes. Only issue in month. But my requirement is to develop in month mode

**Comment by acro5piano** [comment]
This is the time you should start using TypeScript. The following code would solve your problem.

```typescript
const eve = [
  {
    key: 101,
    title: 'techhhh-tech',
    course_name: 'techhhh',
    subject_name: 'tech',
    branch_name: 'Bazaar',
    class_timing_name: 'weekday',
    trainer_name: { id: 100, username: 'trainer@gmail.com' },
    start: '2022-09-10',
    end: '2022-09-10',
  },
  {
    key: 102,
    title: 'tech-tech',
    course_name: 'tech',
    subject_name: 'tech',
    branch_name: 'bazzar',
    class_timing_name: 'weekday',
    trainer_name: { id: 102, username: 'trainerk@gmail.com' },
    start: '2022-08-10',
    end: '2022-08-10',
  },
  {
    key: 103,
    title: 'big data',
    course_name: 'big data',
    subject_name: 'science',
    branch_name: 'Karnataka',
    class_timing_name: 'weekday',
    trainer_name: { id: 103, username: 'trainer2@gmail.com' },
    start: '2022-08-10',
    end: '2022-08-10',
  },
].map((event) => ({ // you should convert Calendar compatible object
    ..event,
    start: new Date(event.start),
    end: new Date(event.end),
}))
```

**Comment by gani419** [comment]
Thank you for the response. I'm working on your solution.

**Comment by gani419** [comment]
It worked in js itself by array.amp(). Thank you for your time.
