### ISSUE TITLE
Increase cell height

### ISSUE THREAD

**Issue by harshanirudh** [acro5piano/react-native-big-calendar#732]
Can i increase cell height so that smaller events can be displayed? . As of now events with 10 mins duration are just shown as line.
edit: hourRowHeight property increase the row size but the hour indicators on the left become invisible

**Comment by acro5piano** [comment]
> edit: hourRowHeight property increase the row size but the hour indicators on the left become invisible

This is probably a bug. Can you reproduce the issue?

**Comment by harshanirudh** [comment]
Sorry, I'm somehow not able to reproduce it now. Will close this issue. Sorry for inconvenience .
