### ISSUE TITLE
Mobile - "month" mode issue

### ISSUE THREAD

**Issue by riyaE2** [acro5piano/react-native-big-calendar#736]
![image](https://user-images.githubusercontent.com/112611651/187852373-a2248695-6424-4a97-97a1-6f15b97cd533.png)

I'm not able to show month name, year, next month, prev month functionality, can you please help to implement this functionality ?

**Comment by acro5piano** [comment]
That is expected. You should implement your own controls. Please refer to the storybook.

https://github.com/acro5piano/react-native-big-calendar/blob/main/stories/full-customization.stories.tsx

Best,
