### ISSUE TITLE
Not showing event when i pass start and end date as a string

### ISSUE THREAD

**Issue by riyaE2** [acro5piano/react-native-big-calendar#744]
const events = [

    {
        title: 'ABCDS',
        start: new Date(2022, 8, 17),
        end: new Date(2022, 8, 28),
    },
    {
        title: 'Meeting',
        start: new Date(2022, 8, 11, 10, 0),
        end: new Date(2022, 8, 11, 10, 30),
    },
]

We are passing array like this then i'm able to show events in calendar but when i'm passsing as follows not able to see any events on calendar

const events = [

    {
        title: 'ABCDS',
        start: "2022-11-26T21:30:00.000Z",
        end: "2022-11-30T05:30:00.000Z",
    },
    {
        title: 'Meeting',
        start: "2022-11-30T05:30:00.000Z",
        end: "2022-11-30T05:30:00.000Z",
    },
]

**Comment by acro5piano** [comment]
You should convert the string into date before passing them into the calendar component. This is by design.
