### ISSUE TITLE
Issue with month mode date calculation and onChangeDate

### ISSUE THREAD

**Issue by juspeeh** [acro5piano/react-native-big-calendar#747]
When mode is month and the days are calculated the last day of the month is always left out. This ends up onChangeDate returning the second last date always. See images:

getDatesInMonth leaves the last day out:
![Screenshot 2022-09-15 at 10 34 59](https://user-images.githubusercontent.com/25384349/190344267-6da0ddbc-c810-4b06-916b-2e526a6312b2.png)

onChangeDate returns the second last day:
![Screenshot 2022-09-15 at 10 35 30](https://user-images.githubusercontent.com/25384349/190344260-6f7a796c-f8c5-4148-9169-d3ef47251a31.png)

**Comment by acro5piano** [comment]
Sorry for my slow response. I'm busy for now and cannot work for this. If you create a pull request, I'm happy to merge it. Thanks!

**Comment by charithAmila** [comment]
Hey @acro5piano Seems this bug is not fixed yet. May I create PR for this?

**Comment by acro5piano** [comment]
@charithAmila Thanks, please go ahead!

**Comment by charithAmila** [comment]
Hey @acro5piano 
PR is ready to review. https://github.com/acro5piano/react-native-big-calendar/pull/937

**Comment by acro5piano** [comment]
Fixed on v4.4.1
