### ISSUE TITLE
is there a way to remove time slots column in week view ?

### ISSUE THREAD

**Issue by mubashiralisiddiqui** [acro5piano/react-native-big-calendar#753]
<img width="319" alt="image" src="https://user-images.githubusercontent.com/16689214/195338513-a878c6b0-2545-410b-83c8-905449e51a56.png">
I wanted to remove hours sections from week view I didn't find any props for that

**Comment by acro5piano** [comment]
Thanks for your interest. It is not possible for now. If you create a pull request, I'm happy to merge it. Thanks

**Comment by mubashiralisiddiqui** [comment]
@acro5piano 
https://github.com/acro5piano/react-native-big-calendar/pull/754
please review and merge it ASAP :)

**Comment by acro5piano** [comment]
@mubashiralisiddiqui Thanks. It is released on v3.3.0

https://github.com/acro5piano/react-native-big-calendar/releases/tag/v3.3.0
