### ISSUE TITLE
In week and day mode events are showing at bottom when using renderEvent prop

### ISSUE THREAD

**Issue by Nikunj-Bisht12** [acro5piano/react-native-big-calendar#777]
![Screenshot from 2022-11-16 12-14-35](https://user-images.githubusercontent.com/104750364/202104945-74ed7e06-f7b0-4e03-85c2-f25db8857424.png)

**Comment by acro5piano** [comment]
I think you don't pass `touchableOpacityProps` correctly. Are you doing the same way as README shown?

```tsx
const renderEvent = (
  event,
  touchableOpacityProps,
) => (
  <TouchableOpacity {...touchableOpacityProps}>
    <Text>{`My custom event: ${event.title} with a color: ${event.color}`}</Text>
  </TouchableOpacity>
)

<Calendar renderEvent={renderEvent} />
```

**Comment by Nikunj-Bisht12** [comment]
@acro5piano 
` <TouchableOpacity
            onPress={() =>{}}
            style={[styles.eventCellStyle, { alignItems: "center", justifyContent: "center" }]}
          >
            <Text
              textStyle={{ marginLeft: 6, textAlign: "center" }}
              textSize={TextSize.ExtraFineSmall}
              fontWeight={FontWeight.Regular}
              testId={""}
            >
              {`+more`}
            </Text>
          </TouchableOpacity>`

**Comment by acro5piano** [comment]
@Nikunj-Bisht12

You should pass `{...touchableOpacityProps}` from props of your custom `renderEvent` function.

```tsx
<TouchableOpacity onPress={() =>{}} style={[styles.eventCellStyle, { alignItems: "center", justifyContent: "center" }]} {...touchableOpacityProps}>
```

**Comment by Nikunj-Bisht12** [comment]
@acro5piano after passing still facing same issue can you share a smple or code snippet of this it will be very helpful

 <TouchableOpacity
            onPress={() =>{}}
            style={[styles.eventCellStyle, { alignItems: "center", justifyContent: "center" }]}

            {...touchableOpacityProps}
          >
