### ISSUE TITLE
Swipe RTL is working fine, but Swipe LTR always goes to previous month last date

### ISSUE THREAD

**Issue by mmujtabam** [acro5piano/react-native-big-calendar#795]
Hi,
@mubashiralisiddiqui and @acro5piano 
**Your last fixes produced following issue.**

Steps to reproduce:

- Open storybook, desktop, iOS or Android in any mode (day, 3 days, week, month view)
- Swipe RTL will work fine and have default behavior
- However, swipe LTR will go to previous month last date in all modes
Please look into this.
Thanks

**Comment by acro5piano** [comment]
Thanks for reporting it. Can you create a PR to fix this? I'm happy to merge if you do so. Thanks!

**Comment by aleksays** [comment]
I created a pull request that fixes this bug. @acro5piano сheck it, please
https://github.com/acro5piano/react-native-big-calendar/pull/797

**Comment by acro5piano** [comment]
Thanks. I'll check it out later 😉

**Comment by acro5piano** [comment]
@aleksays A happy new year! I've reviewed the PR.

**Comment by acro5piano** [comment]
This issue was introduced in #764. I'm digging into the original issue and reverting changes, without re-create the issue.

**Comment by acro5piano** [comment]
The fix was released on v3.3.2 !

@mmujtabam @aleksays
Please check the latest version. If you have any problem with it, let me know. Thanks!
