### ISSUE TITLE
Calendar Left swipe issue

### ISSUE THREAD

**Issue by ronakbuoyancy** [acro5piano/react-native-big-calendar#805]
Hi, In Big-Calendar,  swipe is not working smooth in mode of month. When I swipe right, swipe smooth but on left swipe it's hang after 3-4 swipes. I upload video and code here,
 
#screen_recording
https://user-images.githubusercontent.com/102415580/210559221-5d9b0df5-7e97-414f-bf22-a34209788c54.mov

#code
 <Calendar
          height={Dimensions.get("window").height - 60}
          events={calendarEvents}
          mode={mode}
          swipeEnabled={true}
          eventCellStyle={getEventColor}
        />

**Comment by acro5piano** [comment]
Are you working for the Web? Also, please make sure you're using the latest version (3.3.2)

**Comment by ronakbuoyancy** [comment]
Thank You for your response. I am working for mobile. I upgraded latest version and problem resolved.

**Comment by acro5piano** [comment]
@ronakbuoyancy Thank you for checking the new version!
