### ISSUE TITLE
Demo url down

### ISSUE THREAD

**Issue by rdewolff** [acro5piano/react-native-big-calendar#806]
The demo URL is not working.

**Comment by acro5piano** [comment]
What do you mean by "the demo URL"?

Storybook url seems working fine: https://react-native-big-calendar.vercel.app

**Comment by rdewolff** [comment]
The [Components Demo](https://react-native-big-calendar.netlify.com/?path=/story/desktop--3days-mode) URL on the top of the readme file 👀

**Comment by acro5piano** [comment]
Thanks! I've fixed the link.

**Comment by rdewolff** [comment]
Great 🙌
