### ISSUE TITLE
Slow Rendering as the number of events increases in week/day view

### ISSUE THREAD

**Issue by nairash94** [acro5piano/react-native-big-calendar#820]
Hi @acro5piano  thanks a lot for creating this library . Much Appreciated!!
I've been noticing the slowness on the iOS IPad simulator whenever i try to change to previous or next week, it takes a lot of time to load the updated calendar component.
I have identified the major bottleneck to be **eventCount** and **eventOrder** props in _renderMappedEvent function in CalendarBody.tsx. This 2 props presently goes through the entire eventList for every single event causing a major lag when the number of events increases to more than 10. So we can make this an optional prop in this function.
if we don't send these props, the performance is improving drastically with less freeze time.
https://github.com/acro5piano/react-native-big-calendar/blob/c027c7aa3ba59b19a0157db1c52858a1993010ad/src/components/CalendarBody.tsx#L120-L138
I know it supports a major feature in this plugin, but i believe it would be really helpful if we can have more control over whether to use it or not.

**Comment by acro5piano** [comment]
Thanks for your PR. I've published v3.4.0 and it will be fixed. Let me know if you have any troubles after updating!

**Comment by marko-mlinarevic** [comment]
I'm having this issue on android. Using your react native demo example. it's very slow couple of seconds to load everything.
