### ISSUE TITLE
Event color props 

### ISSUE THREAD

**Issue by nicolas-chalant** [acro5piano/react-native-big-calendar#823]
### Event color props

Hello @acro5piano , 

Thank you for your work on this project ! 

I was wondering if there are any props to handle the color of the events on the calendar ? 
Here is an example of what I did on my react website (using react-big-calendar), I was trying to do the same on the mobile app but I did not find any props that allow me to do so.

![image](https://user-images.githubusercontent.com/73187667/216939280-56e22af7-cbd0-4509-806c-f46f709729aa.png)

As you change the color of the event when they overlap I thought you might have a prop that I did not find that could help me.

Thanks once again for this calendar
Nicolas

PS : I'm on Android

**Comment by acro5piano** [comment]
Hi @nicolas-chalant , the prop `eventCellStyle` should be what you are looking for. It accepts both style object or function which returns style object.
If you require to fully customize the cell, use `renderEvent` instead.

**Comment by nicolas-chalant** [comment]
Thank you for your quick response, it is working well. 
I don't know how I missed it in the documentation, sorry I wasted your time

**Comment by acro5piano** [comment]
No worries, glad to hear that!

**Comment by nicolas-chalant** [comment]
On my previous answer, I tried to change the style with the prop eventCellStyle, which worked, but it changed all events together.
My goal is to have different colors based on the type of the event. 

I have a function that returns the style based on the type, but eventCellStyle takes only one style, right ? 
I cannot give it an array or anything that could take multiple styles in order to have a specific style on an event, or am I missing something ?

**Comment by josh-thompson13** [comment]
Any updates for customising color of each event?
