### ISSUE TITLE
Event cell color different for each event (issue #823 follow up)

### ISSUE THREAD

**Issue by nicolas-chalant** [acro5piano/react-native-big-calendar#825]
Hello @acro5piano, 

On my previous answer on the #823 issue, I tried to change the style with the prop eventCellStyle, which worked, but it changed all events colors at the same time.
My goal is to have different colors based on the type of the event.

I have a function that returns the style based on the type, but eventCellStyle takes only one style, right ?
I cannot give it an array (or a prop color on each event) that could take multiple styles in order to have a specific style on an event, or am I missing something ?

I also tried to give a look at EventRenderer, but it seems that your stroybook is no longer found on github [https://github.com/acro5piano/react-native-big-calendar/blob/main/stories/index.stories.tsx](url)
![image](https://user-images.githubusercontent.com/73187667/217211896-60d5d989-0bfd-49df-b909-ce7bf4498ff7.png)

**Comment by acro5piano** [comment]
Thanks for your issue.

> I have a function that returns the style based on the type, but eventCellStyle takes only one style, right ?

I didn't notice this, but yes. I'll the code to enable to have multiple styles soon.

> I also tried to give a look at EventRenderer, but it seems that your stroybook is no longer found on github

Fixed!

**Comment by acro5piano** [comment]
Fixed on v3.4.1, without changing code. It was just type-changed.

@nicolas-chalant Can you try the new version? It might work only on the Web platform. Thanks

**Comment by nicolas-chalant** [comment]
Thanks for the update, I'm checking it !

**Comment by josh-thompson13** [comment]
> With the storybook I reached my goal ! Thanks again for your help.
> 
> I did not need the style array actually, but I tried it and it seems to work.
> 
> For those wondering, I used a customize event with a color prop and add those lines in the calendar :
> 
> ```
> eventCellStyle={(event) => {
>       const backgroundColor = event.color
>       return { backgroundColor }
> }}
> ```
> 
> ![Screenshot_20230209-151932](https://user-images.githubusercontent.com/73187667/217839496-3ba53aac-c5b7-416a-859a-59f336ae6a87.png)

How did you do this? Can you please share the storybook you're referring to? :)

**Comment by josh-thompson13** [comment]
Hello @acro5piano  @nicolas-chalant,
Firstly, thank you for this component, very useful.
I am wondering if it is possible to set the event color based on the data passed in. For example my dataset looks something like this:
{title: "meeting",start:new Date(), end: new Date(), color:"red"}

Is it possible to set the calendar entry color to match the color property in my object? If so, how? 

Thank you!
