### ISSUE TITLE
eventCellStyle takes only view style (can't change text style of an event)

### ISSUE THREAD

**Issue by nicolas-chalant** [acro5piano/react-native-big-calendar#828]
Hi again @acro5piano,

I noticed that eventCellStyle only takes view style `ViewStyle | (event: ICalendarEvent<T>) => ViewStyle`, which means that we can't change the font size, color or even family of the event text.

Should I use another prop to change those styles ?

I hope I'm not taking too much of your time with all of my questions the last few days..

Thanks once again for your work
Nicolas

**Comment by acro5piano** [comment]
Yes that is a intended behavior. `eventCellStyle` is just a prop for wrapping `TouchableOpacity` style.

If you want to fully customize the event cell, please use the `renderEvent` prop instead. It's much more flexible.
