### ISSUE TITLE
Error when building to web

### ISSUE THREAD

**Issue by wseow87** [acro5piano/react-native-big-calendar#851]
Hi,

I am using react-native-web in my application.
When building to web, I am facing following error:

ERROR in ./node_modules/react-native-big-calendar/build/index.es.js 1:40481-40526
Module not found: Error: Package path ./dist/index.es is not exported from package ...\node_modules\merge-anything (see exports field in ...\node_modules\merge-anything\package.json)

Below is my webpack.config.js

```js
const path = require('path');

const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

const appDirectory = path.resolve(__dirname);
const { presets } = require(`${appDirectory}/babel.config.js`);

const compileNodeModules = [
  // Add every react-native package that needs compiling
  // 'react-native-gesture-handler',
  'react-native',
  '@react-native-community',
].map(moduleName => path.resolve(appDirectory, `node_modules/${moduleName}`));

const fontLoaderConfiguration = {
  test: /\.ttf$/,
  loader: 'url-loader', // or directly file-loader
  include: path.resolve(__dirname, 'node_modules/react-native-vector-icons'),
};

const babelLoaderConfiguration = {
  test: /\.js$|tsx?$/,
  // Add every directory that needs to be compiled by Babel during the build.
  include: [
    path.resolve(__dirname, 'index.web.js'), // Entry to your application
    path.resolve(__dirname, 'App.web.tsx'), // Change this to your main App file
    //path.resolve(__dirname, 'App.tsx'),
    path.resolve(__dirname, 'src'),
    ...compileNodeModules,
  ],
  use: {
    loader: 'babel-loader',
    options: {
      cacheDirectory: true,
      presets,
      plugins: ['react-native-web'],
    },
  },
};

const svgLoaderConfiguration = {
  test: /\.svg$/,
  use: [
    {
      loader: '@svgr/webpack',
    },
  ],
};

const imageLoaderConfiguration = {
  test: /\.(gif|jpe?g|png)$/,
  use: {
    loader: 'url-loader',
    options: {
      name: '[name].[ext]',
    },
  },
};

module.exports = {
  entry: {
    app: path.join(__dirname, 'index.web.js'),
  },
  output: {
    path: path.resolve(appDirectory, 'dist'),
    // publicPath needs to be ./ for the build to work properly, but doesn't work with DEV
    publicPath: '/',
    filename: 'bundle.js',
  },
  resolve: {
    extensions: ['.web.tsx', '.web.ts', '.tsx', '.ts', '.web.js', '.js'],
    alias: {
      'react-native$': 'react-native-web',
    },
  },
  module: {
    rules: [babelLoaderConfiguration, imageLoaderConfiguration, svgLoaderConfiguration, fontLoaderConfiguration],
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: path.join(__dirname, 'index.html'),
    }),
    new webpack.DefinePlugin({
      // See: https://github.com/necolas/react-native-web/issues/349
      __DEV__: JSON.stringify(true),
    }),
  ],
};
```

**Comment by acro5piano** [comment]
@wseow87 
Thanks for reporting this.

What happens if you edit `node_modules/react-native-big-calendar/build/index.js` line 1101

```tsx
// Since Metro Bundler does not load .cjs and .es.js files, we should require it like this.
// It is still possible to use .cjs by changing Metro config, but it forces library users to take an additional step.
// So this workaround is better.
var merge = require('merge-anything/dist/index.es').merge;
```

into

```tsx
// Since Metro Bundler does not load .cjs and .es.js files, we should require it like this.
// It is still possible to use .cjs by changing Metro config, but it forces library users to take an additional step.
// So this workaround is better.
var merge = require('merge-anything/dist/index.cjs').merge;
```

If it does not fix the issue, I'll stop using that library as it emits similar errors previously.

**Comment by wseow87** [comment]
Hi @acro5piano 

Thanks for the suggestion.
Unfortunately, changing  `node_modules/react-native-big-calendar/build/index.js` do not make a difference.

However, i had to take a different approach to change `node_modules/react-native-big-calendar/build/index.es.js` .
What i did is to add the following line at the top of the file:

> import { merge } from 'merge-anything';

and i commented the line below:

> //var merge = require('merge-anything/dist/index.es').merge;


The compilation works fine with the changes above.

**Comment by acro5piano** [comment]
Thank you. That's a good suggestion for those who have the same problem.

At the same time, I'll create our own `merge` function instead of using a library. That might reduce bundle size well and dismisses this issue.
After that, I'll close this issue.

**Comment by kjkurtz** [comment]
I ran into the same issue, so would definitely appreciate removing that library as a dependency. Thanks!

**Comment by ardegirmencioglu** [comment]
Hi folks,

I am getting same error and couldn't solve it. Do you have any suggestions? A week ago it was working perfectly but now nextjs build getting error at below.

./node_modules/react-native-big-calendar/build/index.js
Module not found: Package path ./dist/index.es is not exported from package C:\Projects\kozmik\lb.core.client\node_modules\merge-anything (see exports field in C:\Projects\kozmik\lb.core.client\node_modules\merge-anything\package.json)

Thanks
