### ISSUE TITLE
Date and time for a specific cell

### ISSUE THREAD

**Issue by IAMNABEEL** [acro5piano/react-native-big-calendar#876]
I wanted to create a meeting by pressing the cell, when using onPressCell, it returns like this "2023-06-12T22:00:00.000Z", but what I was is exact datetime for specific cell to create meeting on that date and time, how do I achieve it, kindly help me.

**Comment by acro5piano** [comment]
You should implement your own `onPressCell` logic. Please refer to the storybook:

- https://github.com/acro5piano/react-native-big-calendar/blob/main/stories/desktop.stories.tsx#L295-L315
- https://github.com/acro5piano/react-native-big-calendar/blob/main/stories/hooks.ts#L8-L18

If you have any questions, feel free to re-open this issue.
