### ISSUE TITLE
Feature: Support onLongPress in month mode

### ISSUE THREAD

**Issue by Letty** [acro5piano/react-native-big-calendar#923]
I've patched your awesome library to test the option of onLongPress for the month mode. This functionality is quite nice to have as a shortcut to add new events.
Is this something you would be interested in? It would also help me to not patch your library all the time on new versions.

**Comment by acro5piano** [comment]
Thank you, please send a pull request!
(I'm busy for my main job, so reviewing take some time though)

**Comment by acro5piano** [comment]
@Letty Thanks! Released on v4.5.0
