### ISSUE TITLE
How can I change the blue active day and the blue background  of event notes?

### ISSUE THREAD

**Issue by Minte-grace** [acro5piano/react-native-big-calendar#93]

**Comment by acro5piano** [comment]
You can set `eventCellStyle` to change the blue background of event notes. You can find a working example here:

https://github.com/llotheo/react-native-big-calendar/blob/master/stories/index.stories.tsx#L61-L69

However, the blue active day cannot be changed for now. I've added the style customization to TODO list.
I'll try to implement the feature when I have time to work on, but your PR is always welcome.

**Comment by Minte-grace** [comment]
Oh thank you ur such a nice guy

**Comment by damian-mac** [comment]
is there an ETA on this feature?

**Comment by acro5piano** [comment]
@damian-mac 
Thanks for the reminder. I can't say exact ETA of this feature, because a refactoring for `style` property is needed. For now, please use `renderEvent` prop.

https://github.com/acro5piano/react-native-big-calendar#eventrenderer

**Comment by damian-mac** [comment]
Thank you so much, much appreciated!

**Comment by acro5piano** [comment]
I'm working on providing theme functionality.

https://github.com/acro5piano/react-native-big-calendar/pull/475

**Comment by acro5piano** [comment]
@damian-mac @Minte-grace 
I'm working on the custom theme functionality. Can you check it? I'll release it as v3.0.0-alpha. Thanks!

https://deploy-preview-475--react-native-big-calendar.netlify.app/?path=/story/desktop--provide-custom-theme

**Comment by acro5piano** [comment]
As I've published `v2.0.0-rc` and implemented this topic, I'll close this issue. If you have bugs on it, feel free to report it!

https://github.com/acro5piano/react-native-big-calendar/releases/tag/v2.0.0-rc

Summary: You can now use `theme` prop. `primary` color will be applied to both the blue active day and background of event. even you can use `renderEvent` to implement it.
