### ISSUE TITLE
How to Modify Header.

### ISSUE THREAD

**Issue by PankajRanaAdglobal** [acro5piano/react-native-big-calendar#932]
How we can modify font of the header and make date scrollable for future and previous date.
Also Please suggest how can we change Calendar Year.

samle code and css:- 
<Calendar
                events={events} height={500}
                headerContainerStyle={styles.calenderContainer}
                dayHeaderHighlightColor={BLACK}
                date={new Date()}
                dayHeaderStyle={styles.dayHeaderStyle}
            />
            
dayHeaderStyle:{
        fontSize:12,
        color:'white',
        backgroundColor:'red'
    }
![image](https://github.com/acro5piano/react-native-big-calendar/assets/141351468/2dd80b6a-3120-4f64-b0dd-9298442c49e6)

**Comment by acro5piano** [comment]
You can use theme feature.

```tsx
const theme = {
  palette: {
    primary: {
      main: 'red',
    },
  },
  typography: {
    xl: {
      fontSize: 12,
    },
  },
}

<Calendar theme={theme} weekDayHeaderHighlightColor={BLACK} ... />
```

> Also Please suggest how can we change Calendar Year.

I don't understand what are you talking about. Just change `date` prop's year and the calendar adjust it.

**Comment by PankajRanaAdglobal** [comment]
Thanks for your replay.

**Comment by PankajRanaAdglobal** [comment]
I have a overlapping issue in events.
How to fix this?

Check for refrence
https://lh7-us.googleusercontent.com/chat_attachment/AFzxxOhKUBvlxqRQI3r7LZihgXJiryoGUiAoqWCO-A8TCIK-AW3vVvuUB_ikKJbclIybz_BOjWohEYgr2ytwdMzE-9v3ee50lC9KWHbIq9yf97hk_He9Wb392TdPVtukT4w-KXt5ghOWqha5ZvXM4qi9Hrs9YgtCiNaFU-P8Fu9oUEZ_Y7BvdEHjK082k9_8KoGHvzZIB0o3pTB6sQT4Oo8bzrFbgCumljgZhEG5ydWOlC4oRg7sLM3Kg0yH9tT0n0Rn4DjkLRF4qMdEWVv9hX8aYL_5p_36GGeyS1rIeIb_KIMn7kh4P6ee3e31v0HzkZsKow=w512

**Comment by PankajRanaAdglobal** [comment]
how to reverse date and day name 

https://lh7-us.googleusercontent.com/chat_attachment/AFzxxOhs6-Tu1nHxALS6FMxIxURyQI8SxSwZfXk30vXk4FmGfqqX2D53zAqLmnugBYzab3AKsnv20Y97iq4pgOGq0ADDUSLTvNypjRxvTMAmU2ogahAy0yFA6iyWKqUV_81UeI_S462-YM5RHjB3PLle9w5-ygb7j28UNOR-nA3RAerKepQ35Mh9PmGLj27CG95JeiOuezst-rzs49er7NXNtcxLDyDLEM1bIJjT58KFDDeyvLIN1gYrCTnB9PtDEZnQ5McJkpDz-QHbsiQDEvWtp2izSD4JbhzZla46lj0exTgEtfeEkiYwfnhE8ND0Vbmmrg=w512

**Comment by acro5piano** [comment]
The link you sent cannot be opened.

This component is intended for imitating Google Calender and too much customization should not be implemented to keep things clean. Currently it has already too much customization options, which makes this lib hard to maintain.

Thus, there is no option to reverse date and day name.

**Comment by PankajRanaAdglobal** [comment]
Hi,
I have updated the image Url. You can check now reference image.
Thanks!
