### ISSUE TITLE
Meeting frequency (Daily,Weekly,Monthly)

### ISSUE THREAD

**Issue by sunilkumawat-07** [acro5piano/react-native-big-calendar#945]
Is this possible to set the frequency in calendar? like google event calendar show meeting if we create a meeting on daily basis the meeting will show every day in the calendar.

![image](https://github.com/acro5piano/react-native-big-calendar/assets/110443677/2f402028-22f8-42cf-9a03-896d3d3d8996)

**Comment by acro5piano** [comment]
Thanks for your suggestion. The feature of recurrent events is a big feature and should be solved in a different library.

My proposal is to use RRule. It is known that Google Calendar internally uses it.

- https://github.com/jkbrzt/rrule
- https://github.com/remotehour/rrule-duration (If you need time range and different timezone support)

**Comment by sunilkumawat-07** [comment]
Thanks for your reply. Can you suggest that how can I implement [https://github.com/jkbrzt/rrule](url) in your **react-native-big-calendar** library.

**Comment by acro5piano** [comment]
@sunilkumawat-07 It depends on your use-case and I cannot say what is the solution. The recurrence is different concern.

I will propose a reference code which is not verified:

```
import { RRule } from 'rrule'
import { CalendarEvent } from 'rrule-duration'
import { Calendar } from 'react-native-big-calendar'

const event = new CalendarEvent({
  start: {
    hour: 10,
    minute: 0,
    tz: 'UTC',
  },
  end: {
    hour: 22,
    minute: 30,
    tz: 'Asia/Tokyo',
  },
  recurrences: [
    new RRule({
      freq: RRule.DAILY,
      byweekday: [RRule.MO, RRule.FR],
    }),
    new RRule({
      freq: RRule.MONTHLY,
      bymonthday: 25,
    }),
  ],
})

const events = event
  .occurences({
    between: [
      new Date('2020-10-01T00:00:00Z'),
      new Date('2020-12-31T00:00:00Z'),
    ],
  })
  .map(([start, end]) => ({ title: '...', start, end }))

// `events` is something like this:
//
//   const events = [
//     {
//       title: '...',
//       start: new Date(2020, 1, 11, 10, 0),
//       end: new Date(2020, 1, 11, 10, 30),
//     },
//     {
//       title: '...',
//       start: new Date(2020, 1, 11, 15, 45),
//       end: new Date(2020, 1, 11, 16, 30),
//     },
//   ]

function App() {
  return <Calendar events={events} height={600} />
}```
