### ISSUE TITLE
onChangeDate not called after date changed from outside

### ISSUE THREAD

**Issue by akrueger90** [acro5piano/react-native-big-calendar#961]
The onChangeDate is only called if I swipe the calendar. In my case I have swipe disabled and change the date by buttons, when I do this, the function is not called. 
It would also be nice to be able to call the swipe left and right methods from the outside programatically.

**Comment by acro5piano** [comment]
I think you can write logic on `useEffect`. 

```tsx

const MyComponent = () => {
}


```

**Comment by akrueger90** [comment]
But the problem is, that onChangeDate is not called if I change the date prop from the outside. I use the feedback from this function to load data for the displayed timeframe. 
This was working in 3.3.0. I guess it got lost in the performance improvements.

**Comment by acro5piano** [comment]
Hmm, I'm not sure what is your specific use-case. If you provide code you're working on, it might be helpful. Also please send a pull request if you can fix it. Thanks

**Comment by acro5piano** [comment]
Please not that bi-directional event handler might be deleted during the process of performance improvement. I think your use-case should be implemented in another way if I understand you correctly.

**Comment by akrueger90** [comment]
I added a PR with a storybook example of my problem. #963

**Comment by acro5piano** [comment]
Thanks for sharing the reproduction code. What I understood fthe issue:

- If `swipeEnabled`, `onChangeDate` will be fired.
- If the date was changed outside the component, `onChangeDate`  will not be fired, regardless of `swipeEnabled`.

https://github.com/acro5piano/react-native-big-calendar/blob/main/src/components/CalendarContainer.tsx#L229-L232

I think the behaviors of `swipeEnabled` and `onChangeDate` are quite complicated and hard to fix right now. Bunch of refactoring is required and it might not be practical (of course, if you are willing to do so, please go ahead!)

So, I'd like to propose to implement your own `useEffect`. It's much predictable.

```tsx
useEffect(() => {
  const end = dayjs(date).add(7, 'days')
}, [date])
```
