### ISSUE TITLE
Schedule mode - color of the items

### ISSUE THREAD

**Issue by voulgarakis** [acro5piano/react-native-big-calendar#965]
Hi all,

is there a way to have custom colors for the events in schedule mode? Just like we have this ability in the other modes.

Thanks

**Comment by acro5piano** [comment]
I think it's working just like in other modes. Did you experience any trouble with it?

ref: https://github.com/acro5piano/react-native-big-calendar/pull/942/files#diff-a8472b0587fd53563ec24beb2d8bcd8f69df800b01221d19aa9c8c9791be9d4cR172

**Comment by voulgarakis** [comment]
yes. I use the same events for day/week/month/schedule modes. But when I change mode to schedule the color for all events is like the main palette color. 

See

![Screenshot_2023-11-07-18-27-41-45_092c8c6176b338010e07c442441991c1](https://github.com/acro5piano/react-native-big-calendar/assets/6053521/616c69ac-111a-4820-901f-2ec294a9f6a5)
![Screenshot_2023-11-07-18-27-48-16_092c8c6176b338010e07c442441991c1](https://github.com/acro5piano/react-native-big-calendar/assets/6053521/55d8dd6d-7fd5-4810-9286-e2d63cecd955)

**Comment by acro5piano** [comment]
@charithAmila Do you have any idea of this issue?

**Comment by charithAmila** [comment]
> @charithAmila Do you have any idea of this issue?

I will take a look.

**Comment by charithAmila** [comment]
Hey @voulgarakis 
Can you provide your code, please?

**Comment by charithAmila** [comment]
Hi @acro5piano 
Raised a PR https://github.com/acro5piano/react-native-big-calendar/pull/970

**Comment by voulgarakis** [comment]
Yes this is the code

**Comment by acro5piano** [comment]
Must be fixed on v4.7.1. Thanks @charithAmila for the fix and @voulgarakis for reporting this.
