### ISSUE TITLE
How to change the Current day name color in month view?

### ISSUE THREAD

**Issue by ImranMunawaar** [acro5piano/react-native-big-calendar#997]
How to change the Current day name in monthView?? @lorenzogatti  @Letty @titanve @fabrianibrahim 
I want to change the current day color right now it's showing blue.
<img width="322" alt="2023-12-28_17-12-19" src="https://github.com/acro5piano/react-native-big-calendar/assets/131453896/9f1d36aa-cc3e-4871-aa07-767421b4b446">

**Comment by ImranMunawaar** [comment]
@acro5piano Please can you help me with this question?

**Comment by acro5piano** [comment]
@ImranMunawaar Hi, a happy new year!

Please set your primary color by providing a theme. use `theme.palette.primary.main`.

For more details, please take a look at the document: https://github.com/acro5piano/react-native-big-calendar?tab=readme-ov-file#theme

If you have further issues, please reopen this thread. Thanks
